name: Publish site
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-java@v4
        name: Setup JDK
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -Pbase_url=https://mattidragon.github.io/JsonPatcherDocs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./build/out/

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-to-github-pages.outputs.page_url }}
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-to-github-pages
        uses: actions/deploy-pages@v4
